
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoghxpsfcswlvzvfkhbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvZ2h4cHNmY3N3bHZ6dmZraGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTYwNDQsImV4cCI6MjA2NTU3MjA0NH0.MVmu2d82EwG0gox1JH91IFsg5RSQYa1n6oUU2C_JFHE";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase URL or Anon Key is missing. Make sure to set them in your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
